### ISSUE TITLE
Widget not working in custom page

### ISSUE THREAD

**Issue by PeranoXx** [bezhanSalleh/filament-google-analytics#11]
I have created new Custom page for google analytics widget but it's not showing up .

![image](https://user-images.githubusercontent.com/89066237/194315259-ca63a6a0-adf7-4d7a-bc7a-8a2e878a5542.png)

![image](https://user-images.githubusercontent.com/89066237/194315461-3e777e2a-7db3-4c5e-a2c3-bb868e6fbd7b.png)

ps: I am still learning filament

**Comment by bezhanSalleh** [comment]
i think you need to enable that from the config
