### ISSUE TITLE
Does not support Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by bartclaeys** [bezhanSalleh/filament-google-analytics#17]
This package relies on Spatie's Laravel Google Analytics package which does not support GA4 and has no plans to support it. Instead it supports the old _Universal Analytics_ which will stop processing data on July 1, 2023:

https://support.google.com/analytics/answer/10089681?hl=en

I hope the creator of this package can update the description with this info so that people don't spent time installing and configuring something that will stop working soon.

**Comment by onodera-punpun** [comment]
Could this issue be reopened, like bartclaeys said, it would prevent people from wasting time installing something that potentially will stop working in a few months. besides that it could also be used to track a possible rewrite to a GA4 compatible library.
