### ISSUE TITLE
Call to undefined function BezhanSalleh\FilamentGoogleAnalytics\gmp_sign()

### ISSUE THREAD

**Issue by Asadbekinha** [bezhanSalleh/filament-google-analytics#26]
Call to undefined function BezhanSalleh\FilamentGoogleAnalytics\gmp_sign() error showing. Why?

**Comment by Saifallak** [comment]
Checkout this : https://stackoverflow.com/questions/46647745/fatal-error-call-to-undefined-function-gmp-sign-in-php
