### ISSUE TITLE
Google Analytics v4 Support

### ISSUE THREAD

**Issue by jcsoriano** [bezhanSalleh/filament-google-analytics#28]
Thank you for the great package!

Spatie has just merged in GA v4 support: https://github.com/spatie/laravel-analytics/pull/475

Can we add GA v4 here as well? :)

**Comment by Saifallak** [comment]
any updates on this? @bezhanSalleh ?


sorry for ping.

**Comment by rafayrty** [comment]
i have made a pull request for this @bezhanSalleh
