### ISSUE TITLE
Call to undefined function BezhanSalleh\FilamentGoogleAnalytics\gmp_sign()

### ISSUE THREAD

**Issue by Palria** [bezhanSalleh/filament-google-analytics#33]
Call to undefined function BezhanSalleh\FilamentGoogleAnalytics\gmp_sign()

I am getting this error when i open google analytics dashboard.

**Comment by fatihmehmetkiris** [comment]
I get this error, too. How did you solve that?

**Comment by fatihmehmetkiris** [comment]
Solution for Xampp
php.ini
extension=gmp
