### ISSUE TITLE
Call to undefined function BezhanSalleh\FilamentGoogleAnalytics\gmp_sign()

### ISSUE THREAD

**Issue by Sabawoon-Khan** [bezhanSalleh/filament-google-analytics#54]
I  am encountering this error, and I have tried different solutions, but I haven't obtained any results.

**Comment by Saifallak** [comment]
Duplicate of 
- https://github.com/bezhanSalleh/filament-google-analytics/issues/19
- https://github.com/bezhanSalleh/filament-google-analytics/issues/26
- https://github.com/bezhanSalleh/filament-google-analytics/issues/33
