### ISSUE TITLE
Permanent 7 in the Avg. Sessions Duration widget

### ISSUE THREAD

**Issue by Haikal-Adityo** [bezhanSalleh/filament-google-analytics#55]
Hello,

I'm currently facing a problem with the Avg. Sessions Duration widget, where it consistently shows a value of 7. I have tried reinstalling the package, but the problem is still there. I have tried this package in another project and its working fine.

Additionally the loading circle in the dropdown is always there, even in my other project.

![image](https://github.com/bezhanSalleh/filament-google-analytics/assets/133017274/63f695ee-529f-44ca-b7a6-bf41d6a372c9)

Thank you for your time.

**Comment by bezhanSalleh** [comment]
might be an issue with your account or cache.
