### ISSUE TITLE
always getting Quota Error: User Rate Limit Exceeded

### ISSUE THREAD

**Issue by Saifallak** [bezhanSalleh/filament-google-analytics#6]
Google
 \ 
Service
 \ 
Exception
PHP 8.0.13
9.8.1
{ "error": { "code": 403, "message": "Quota Error: User Rate Limit Exceeded.", "errors": [ { "message": "Quota Error: User Rate Limit Exceeded.", "domain": "usageLimits", "reason": "userRateLimitExceeded" } ] } }

**Comment by abdulmejidshemsu** [comment]
Any idea on the above?

**Comment by Saifallak** [comment]
> Any idea on the above?

Nope, there no sol. For now

Check this thread for more info
https://discord.com/channels/883083792112300104/947955402732109844/1006355115730550834

**Comment by Saifallak** [comment]
Is this fixed? @bezhanSalleh

**Comment by bezhanSalleh** [comment]
Haven't really faced this issue on my 2 dozen projects. And given that I'll be moving from UA towards GA4 not planning on digging into it anymore.

**Comment by Saifallak** [comment]
Oki, but don't think spatie have any plans for ga4 ..

**Comment by bezhanSalleh** [comment]
I do though 😇

**Comment by Saifallak** [comment]
Great, best luck for you
