### ISSUE TITLE
For some reason the widgets do not render anything

### ISSUE THREAD

**Issue by timlalev** [bezhanSalleh/filament-google-analytics#63]
Filament 3. Installed package added json credential and published the config file and set the property id. Added the widgets to the filament dashboard page but there is absolutely nothing rendered on the page and no errors either.  So not sure what is going on. 
Inside the panel I try to use the widgets like so:
`
->widgets([
      Widgets\AccountWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\PageViewsWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\VisitorsWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\ActiveUsersOneDayWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\ActiveUsersSevenDayWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\ActiveUsersTwentyEightDayWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\SessionsWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\SessionsDurationWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\SessionsByCountryWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\SessionsByDeviceWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\MostVisitedPagesWidget::class,
      \BezhanSalleh\FilamentGoogleAnalytics\Widgets\TopReferrersListWidget::class,
      // Widgets\FilamentInfoWidget::class,
])
`
But I get an empty page:

<img width="1214" alt="Screenshot 2024-04-26 at 3 40 30 PM" src="https://github.com/bezhanSalleh/filament-google-analytics/assets/11634736/854482a1-8381-4bbb-8e8d-0d36cb390d9f">

**Comment by aymanalhalali** [comment]
Same issue, any updates?

**Comment by ZayRTun** [comment]
Hi, same issue here, using filament 3.

**Comment by gieter-solutions** [comment]
Change the filament_dashboard variable in the 'filament-google-analytics.php' config file to true for each of the widgets you want to show on your Filament dashboard. Currently your CanView trait is returning false.

**Comment by jhoanborges** [comment]
> Change the `filament_dashboard` variable in the 'filament-google-analytics.php' config file to true for each of the widgets you want to show on your Filament dashboard. Currently your CanView trait is returning false.

worked. This should be in the docs.
