### ISSUE TITLE
can we show mobile app statistics instead of website statistics ?

### ISSUE THREAD

**Issue by Saifallak** [bezhanSalleh/filament-google-analytics#74]
can we show mobile app statistics instead of website statistics ?

**Comment by bezhanSalleh** [comment]
> can we show mobile app statistics instead of website statistics ?

you might be asking something else but as far as I know, it would be the same setup for both. though there might be some extra steps for integrating with a mobile app but for reports which the plugin provides as widgets; you would only need to add/use those specific metrics and dimenstions and then build your own widgets.
